### ISSUE TITLE
SP Simulator: Document the hardcoded rules in the simulator

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-sp-simulator#8]
Make a list of the rules and with each condition, for each rule add the file where the rule was implemented.
Short manual in how to add new rules.

**Comment by agalaguz** [comment]
@brunosmm @eudisley 
Hardcoded items for all simualtors.
https://docs.google.com/document/d/1p3HK_Z6ZMex6KOeeqJ1eHP-zkpPUVgfRIEQ4MN081eY/edit?usp=sharing
